id: I8FBB8BF9
legacy_id: P009254
ocr_import_info:
  bdrc_scan_id: W1KG3668
  source: bdrc
  ocr_info:
    timestamp: '2020-03-25T00:05:49'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T15:12:57.789820+00:00'
last_modified: 2022-08-31 23:13:01.902340
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG3668
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG3668
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཟབ་མོ་ནང་དོན་གྱི་རྩ་རིས།
  author: འཇམ་མགོན་ཀོང་སྤྲུལ་བློ་གྲོས་མཐའ་ཡས།
statistics:
  ocr_word_mean_confidence_index: 0.8122958430076141
  ocr_word_median_confidence_index: 0.9300000071525574
quality: null
bases:
  I1KG3693:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG3693
      total_pages: 22
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG3693.txt
    statistics:
      ocr_word_median_confidence_index: 0.9300000071525574
      ocr_word_mean_confidence_index: 0.8122958430076141
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
