id: I8FBB8BF9
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T00:05:55+00:00'
last_modified: '2022-06-08T09:42:54.618093+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG3668
  title: ཟབ་མོ་ནང་དོན་གྱི་རྩ་རིས་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    CA42:
      image_group_id: I1KG3693
      title: ''
      total_pages: 22
      order: 1
      base_file: CA42.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
