id: P009254
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG3668
  title: ཟབ་མོ་ནང་དོན་གྱི་རྩ་རིས་
  author: ''
  volumes:
    88bce7f5537d49d4ba9d11e2fe4e1017:
      image_group_id: I1KG3693
      title: ''
      volume_number: 1
      total_pages: 22
