id: P009254
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-19 19:30:10.856115
source_metadata:
  id: bdr:W1KG3668
  title: ཟབ་མོ་ནང་དོན་གྱི་རྩ་རིས་
  author: ''
  volumes:
    88bce7f5537d49d4ba9d11e2fe4e1017:
      image_group_id: I1KG3693
      title: ''
      volume_number: 1
      total_pages: 22
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
